### ISSUE TITLE
用linear-gradient实现背景中线

### ISSUE THREAD

**Issue by Jenna-u** [huzhijuan77/resume#8]
## 类似需求：
![image](https://user-images.githubusercontent.com/12255714/42633453-26781b86-8613-11e8-8685-7b75a296a9a4.png)

## 实现方案：
1. css 设置`1px`高度，背景色设置（需要2个div）
2. css 设置宽度，`border-bottom: 1px solid #000` (需要2个div)
3. css3 背景线性渐变 (一个就足矣)

## 样式实现：
``` css
.first {
  width: 300px;
  height: 1px;
  background: #fff;
}

.second {
  width: 300px;
  border: 1px solid #fff
}

/*最终效果展示：https://codepen.io/anon/pen/NBqpEa*/
.third {
  width: 300px;
  height: 20px;
  background: linear-gradient(to bottom, white 9px, black 1px, white 10px);
}
```

css`linear-gradient()`函数用于创建多种颜色的线性渐变。包含三个值：
1. 起始轴位置，可以使用角度(0-360deg), 也可以是从上到下(to [top, right, bottom, left])
2. 颜色 (color 10px)从高度为10px的位置开始渐变
3. 结束颜色  最终渐变到结束颜色值

## 举个MDN栗子：
```css
/* 渐变轴为45度，从蓝色渐变到红色 */
linear-gradient(45deg, blue, red);

/* 从右下到左上、从蓝色渐变到红色 */
linear-gradient(to left top, blue, red);

/* 从下到上，从蓝色开始渐变、到高度40%位置是绿色渐变开始、最后以红色结束 */
linear-gradient(0deg, blue, green 40%, red);
```

## 参考：
1.https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient
